server:
    port: ${PORT:8761}

## Classic Eureka configuration
eureka:
    instance:
        hostname: ${HOSTNAME:localhost}
        prefer-ip-address: true

    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://${eureka.instance.hostname}:${server.port}/eureka}
