server:
    port: ${PORT:8010}

## Classic Eureka configuration
eureka:
    instance:
        preferIpAddress: true
        hostname: ${HOSTNAME:localhost}
        statusPageUrlPath: ${HOSTNAME:localhost}/info
        healthCheckUrlPath: ${HOSTNAME:localhost}/health

    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

    server:
        renewal-percent-threshold: 0.90